//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyRespons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyRespons()
        {
            this.ResponseAnswers = new HashSet<ResponseAnswer>();
        }
    
        public int ResponseId { get; set; }
        public int SurveyId { get; set; }
        public string FromIp { get; set; }
        public System.DateTime DateSubmitted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseAnswer> ResponseAnswers { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
